- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ client }}-service"
        namespace: "{{ client }}-system"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
      spec:
        rules:
        - host: "{{ client }}-website.vnf.local"
          http:
            paths:
            - pathType: Prefix #Exact
              path: "/"
              backend:
                service:
                  name: "{{ client }}-service"
                  port:
                    number: 80


