- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ client }}-pv"
      spec:
        capacity:
          storage: 10Mi
        accessModes:
          - ReadWriteMany
        hostPath:
          path: "/data/{{ client }}"

