- name: Create a namespace²
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ client }}-system"
        labels:
          app: "{{ client }}"



